# Generated by Django 5.1.1 on 2024-10-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='ProfilePhoto',
            new_name='profile_photo',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='PhoneNumber',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='SortId',
        ),
        migrations.AddField(
            model_name='customer',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
