# Generated by Django 5.1.1 on 2024-10-05 07:49

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_rename_profilephoto_customer_profile_photo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='Description',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
    ]
