# Generated by Django 5.1.1 on 2024-10-04 07:26

import datetime
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Login',
            fields=[
                ('SortId', models.DateTimeField(default=datetime.datetime.now, editable=False)),
                ('LoginId', models.CharField(default=uuid.uuid4, editable=False, max_length=50, primary_key=True, serialize=False)),
                ('UserId', models.CharField(max_length=50)),
                ('EmailId', models.CharField(max_length=150)),
                ('Password', models.CharField(max_length=300)),
                ('Status', models.IntegerField(default=0)),
            ],
        ),
    ]
